Handle 204 status code
Vonage/vonage-node-sdk pull request #155
Opened 2017-10-16 07:31 UTC by AverageMarcus

When updating a call a 204 response is returned (such as when hanging up an active call). Currently this is seen as an error by the lib but the action does perform correctly but doesn't provide any response body.

(Created again after messing up #154.)

2017-10-16 09:59 UTC, AlexLakatos commented
Thanks @AverageMarcus ! Continuing the discussion from #154 ,agreed with @judy2k that a `204` should return null.

2017-10-16 10:01 UTC, AlexLakatos requested changes

2017-10-16 10:01 UTC, AlexLakatos commented on src/HttpClient.js
> +        response = data;
can we return `null` here instead please?

2017-10-16 10:01 UTC, AlexLakatos commented on test/HttpClient-test.js
> +  it ('should parse a 204 status code as a JSON object', function() {
and update the test as well. We shouldn't parse a `204` as JSON

2017-10-16 10:36 UTC, AlexLakatos approved these changes

2017-11-27 13:33 UTC, merged

2017-11-27 14:13 UTC, mheap commented
LGTM - I've merged it in to master. Thanks @AverageMarcus!