Conversation API
Vonage/vonage-node-sdk pull request #157
Opened 2017-10-17 16:00 UTC by AlexLakatos

Don't merge into master, just review please.

2017-10-20 20:52 UTC, TheChrisVela requested changes

2017-10-20 20:52 UTC, TheChrisVela commented on README.md
> +<!-- TODO: uncomment when the API is fixed
I don't know how I feel about leaving TODOs in documentation. We could keep these changes on a branch and merge in when it's fixed

2017-10-20 20:52 UTC, TheChrisVela commented on README.md
> +<!-- TODO: uncomment when the API is fixed
again, TODO comment

2017-10-20 20:52 UTC, TheChrisVela commented on examples/ex-add-members.js
> +  nexmo.conversations.members.add(config.CONVERSATION_ID, {"action":"join", "user_id":config.USER_ID, "channel":{"type":"app"}}, callback);
why not use readline to get the CONVERSATION_ID or the USER_ID?

2017-10-20 20:52 UTC, TheChrisVela commented on examples/ex-create-read-update-delete-conversation.js
> +    // .then(function(getResp) {
I think instead of having one example file for create-read-update-delete we could split this into a few files.

2017-10-20 20:52 UTC, TheChrisVela commented on examples/ex-create-user.js
> +  nexmo.users.create({name: new Date().getTime().toString()}, callback);
Maybe we should spell out to the user that this is a temp name like in https://github.com/Nexmo/nexmo-node/pull/157/files#diff-ee17179159b8bd766104329f8b53de05R18

2017-10-20 20:52 UTC, TheChrisVela commented on examples/ex-delete-user.js
> +  nexmo.conversations.delete(config.USER_ID, callback);
Use `readline` instead of `config`?

2017-10-20 20:52 UTC, TheChrisVela commented on examples/ex-get-conversation.js
> +  nexmo.conversations.get(config.CONVERSATION_ID, callback);
Use `readline` instead of `config`?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/ex-get-member.js
> +  nexmo.conversations.members.get(config.CONVERSATION_ID, config.MEMBER_ID, callback);
Use `readline` instead of `config`?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/ex-get-members.js
> +  nexmo.conversations.members.get(config.CONVERSATION_ID, {}, callback);
Use `readline` instead of `config`?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/ex-get-user-conversations.js
> +  nexmo.users.getConversations(config.USER_ID, callback);
Use `readline` instead of `config`?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/ex-get-user.js
> +  nexmo.users.get(config.USER_ID, callback);
Use `readline` instead of `config`?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/ex-update-conversation.js
> +  nexmo.conversations.update(config.CONVERSATION_ID, {display_name: "not another convo"}, callback);
I think the `display_name` could be made a bit more specific than "not another convo"

Use `readline` instead of `config`?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/ex-update-user.js
> +  nexmo.users.update(config.USER_ID, {name: new Date().getTime().toString()}, callback);
Use `readline` instead of `config`?
Maybe we should spell out to the user that this is a temp name like in https://github.com/Nexmo/nexmo-node/pull/157/files#diff-ee17179159b8bd766104329f8b53de05R18

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/run-examples.js
> +  // // 'ex-make-call.js',
Remove `//` double comment?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/run-examples.js
> +  // // 'ex-dtmf-to-call.js',
Remove `//` double comment?

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/run-examples.js
> +  //'ex-create-read-update-delete-conversation.js'
spacing

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/run-examples.js
> +  //'ex-add-members.js',
spacing

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/run-examples.js
> +  //'ex-create-conversation.js',
spacing

2017-10-20 20:52 UTC, ChrisGuzman commented on examples/run-examples.js
> +  //'ex-get-user-conversations.js'
spacing

2017-10-20 20:52 UTC, ChrisGuzman commented on src/Conversations.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation to update.
[Doesn't [] mean optional?](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values) is conversationId optional?

2017-10-20 20:52 UTC, ChrisGuzman commented on src/Conversations.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation to delete.
Is converationId optional?

2017-10-20 20:52 UTC, ChrisGuzman commented on src/Members.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation
is conversatId optional?

2017-10-20 20:52 UTC, ChrisGuzman commented on src/Members.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation
is conversationId optional?

2017-10-20 20:52 UTC, ChrisGuzman commented on src/Users.js
> +     * @param {string} [userId] - The unique identifier for the user to update.
is userId optional?

2017-10-20 20:52 UTC, ChrisGuzman commented on src/Users.js
> +     * @param {string} [userId] - The unique identifier for the user to delete.
is userId optional?

2017-10-20 20:52 UTC, ChrisGuzman commented on e2e/conversations.spec.js
> +        nexmo.conversations.get(config.CONVERSATION_ID, (error, result) => {
Ah, is this why the converationId and userId are in the config?

2017-10-20 20:53 UTC, ChrisGuzman commented
Could we `console.log` the responses in the examples? I think it could help the reader to see something when they run the examples on their console

2017-10-22 11:51 UTC, AlexLakatos commented on README.md
> +<!-- TODO: uncomment when the API is fixed
It's commented out anyway. I feel leaving them in a branch would make it harder to merge later and we'd be more likely to forget about them.

2017-10-22 11:52 UTC, AlexLakatos commented on e2e/conversations.spec.js
> +        nexmo.conversations.get(config.CONVERSATION_ID, (error, result) => {
yeah, they are meant to be ran automatically, not from the command line.

2017-10-22 11:53 UTC, AlexLakatos commented on examples/ex-add-members.js
> +  nexmo.conversations.members.add(config.CONVERSATION_ID, {"action":"join", "user_id":config.USER_ID, "channel":{"type":"app"}}, callback);
they are meant to be ran automatically, not from the command line.

2017-10-22 11:53 UTC, AlexLakatos commented on examples/ex-create-read-update-delete-conversation.js
> +    // .then(function(getResp) {
there are already separate files. This is just sort of an end-to-end example. We're doing the same for applications.

2017-10-22 11:57 UTC, AlexLakatos commented on examples/ex-create-user.js
> +  nexmo.users.create({name: new Date().getTime().toString()}, callback);
That just adds extra code in there. The reason https://github.com/Nexmo/nexmo-node/pull/157/files#diff-ee17179159b8bd766104329f8b53de05R18 uses a variable "temp" is because it's referenced a few times in the code and changed later on. If we really wanted to spell this out it would be `randomName` rather than `tempName`, we're  not doing anything with it later. I'm happy leaving this as is.

2017-10-22 11:58 UTC, AlexLakatos commented on examples/ex-delete-user.js
> +  nexmo.conversations.delete(config.USER_ID, callback);
we're running them from `run-examples.js` and not from the command line.

2017-10-22 11:58 UTC, AlexLakatos commented on examples/run-examples.js
> +  // // 'ex-dtmf-to-call.js',
nice catch!

2017-10-22 12:02 UTC, AlexLakatos commented on src/Conversations.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation to update.
yeah [] is optional, but conversationId isn't optional. nice catch.

2017-10-22 12:02 UTC, AlexLakatos commented on src/Conversations.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation to delete.
no, my bad

2017-10-22 12:03 UTC, AlexLakatos commented on src/Members.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation
no, my bad

2017-10-22 12:03 UTC, AlexLakatos commented on src/Members.js
> +     * @param {string} [conversationId] - The unique identifier for the conversation
no, my bad

2017-10-22 12:03 UTC, AlexLakatos commented on src/Users.js
> +     * @param {string} [userId] - The unique identifier for the user to update.
no, my bad

2017-10-22 12:03 UTC, AlexLakatos commented on src/Users.js
> +     * @param {string} [userId] - The unique identifier for the user to delete.
no, my bad

2017-10-22 23:56 UTC, ChrisGuzman commented on README.md
> +<!-- TODO: uncomment when the API is fixed
Ok

2017-10-22 23:57 UTC, ChrisGuzman commented on e2e/conversations.spec.js
> +        nexmo.conversations.get(config.CONVERSATION_ID, (error, result) => {
Hmm, as a user I think it would be nice to have the option to run them from the command line, but maybe that's better for a quickstart in the nexmo-community org

2017-10-22 23:59 UTC, ChrisGuzman commented on examples/ex-create-read-update-delete-conversation.js
> +    // .then(function(getResp) {
If it's end to end then why is part of this commented out?

2017-10-22 23:59 UTC, ChrisGuzman commented on examples/ex-create-read-update-delete-conversation.js
> +    // .then(function(getResp) {
If it's end to end then why is this part of this commented out?

2017-10-23 00:00 UTC, ChrisGuzman commented on examples/ex-create-user.js
> +  nexmo.users.create({name: new Date().getTime().toString()}, callback);
OK

2017-11-30 12:30 UTC, mheap requested changes

2017-11-30 12:30 UTC, mheap commented on examples/ex-create-read-update-delete-conversation.js
> +  var conversations = Promise.promisifyAll(nexmo.conversations);
If we encourage people to use promises, we should bake promise support in to the library. Otherwise our examples should use callbacks

2017-11-30 12:30 UTC, mheap commented on examples/ex-create-conversation.js
> +  nexmo.conversations.create({display_name: 'testing'}, callback);
Add an example callback, showing which parameters are available in the response

2017-11-30 12:30 UTC, mheap commented on e2e/users.spec.js
> +            name: new Date().getTime().toString()
Could we save this in a variable and assert the name returned once the user's been created?

2017-11-30 12:30 UTC, mheap commented on e2e/calls.spec.js
> +  xit('should allow a call to be created', (done) => {
It'd be good if we worked with routing to get Nexmo->Nexmo calls activated on an account so that we can run this in an automated fashion

2017-11-30 12:30 UTC, mheap commented on e2e/members.spec.js
> +            "channel": {
What other channels are there?

2017-11-30 12:30 UTC, mheap commented on e2e/users.spec.js
> +        nexmo.users.get({}, (error, result) => {
Should we allow `nexmo.users.get(function(err, result){});` for getting all users?

2017-11-30 12:30 UTC, mheap commented on examples/ex-create-user.js
> +  nexmo.users.create({name: new Date().getTime().toString()}, callback);
+1 for saving it to a variable to show intent. Although we know that it's just a string to identify a user, someone reading it for the first time may not understand. Perhaps add a fixed string too:

```
let userName = "TestUser-" + (new Date().getTime().toString());
```

2017-11-30 12:30 UTC, mheap commented on examples/ex-update-conversation.js
> +  nexmo.conversations.update(config.CONVERSATION_ID, {display_name: "not another convo"}, callback);
👍 

```
nexmo.conversations.update(config.CONVERSATION_ID, {display_name: "Updated Name Here"}, callback);
 ```

2017-11-30 12:30 UTC, mheap commented on package.json
> +    "test-e2e": "npm run compile && mocha --compilers ./node_modules/.bin/_mocha --compilers js:babel-register ./e2e/*.spec.js",
Duplicate?

2017-11-30 12:30 UTC, mheap commented on src/Conversations.js
> +        var config = {
We can probably extract `config` generation in to something like the following:

```
getRequestConfig(verb, path, params) {
    return {
        host: 'api.nexmo.com',
        path: path,
        method: verb,
        body: params,
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${this.creds.generateJwt()}`
        }
}
```

2017-11-30 12:30 UTC, mheap commented on src/Conversations.js
> +        this._nexmo.getWithQuery(Conversations.PATH, query, this.creds, this.options, callback)
It'd be good if we could stop relying on `this._nexmo`. Maybe move `getWithQuery` in to HTTPClient?

2017-11-30 12:30 UTC, mheap commented on src/index.js
> +exports.getWithQuery = function(path, query, creds, opts, callback) {
We should definitely move this in to `HTTPClient` as it's a new piece of code

2017-11-30 12:30 UTC, mheap commented on test/Conversations-test.js
> +        httpClientStub = sinon.createStubInstance(HttpClient);
👍 for using sinon

2017-11-30 12:30 UTC, mheap commented on test/Conversations-test.js
> +        expect(httpClientStub.request).to.have.been.calledWith(sinon.match(expectedRequestArgs), emptyCallback);
Would we be better using `sinon.mock()` and `mock.verify()` here?

2017-11-30 12:30 UTC, mheap commented on test/Conversations-test.js
> +describe('Conversations', () => {
In general for these tests: 

As well as asserting that the request would have been made, return an expected response from the stub and make sure our code works as expected with that format.

2017-11-30 12:30 UTC, mheap commented on test/Members-test.js
> +describe('Members', () => {
Same as conversations - add responses to our stubs and make sure the code behaves with the correct response

2017-11-30 12:30 UTC, mheap commented on test/Users-test.js
> +describe('Users', () => {
Same as conversations - add responses to our stubs and make sure the code behaves with the correct response

2017-11-30 12:30 UTC, mheap commented on test/Conversations-test.js
> +    privateKey: __dirname + '/private-test.key'
Use `path.join` for Windows users

2017-11-30 12:30 UTC, mheap commented on test/Members-test.js
> +    privateKey: __dirname + '/private-test.key'
Use `path.join` for Windows users

2017-11-30 12:30 UTC, mheap commented on test/Users-test.js
> +    privateKey: __dirname + '/private-test.key'
Use `path.join` for Windows users

2017-11-30 12:30 UTC, mheap commented on test/Conversations-test.js
> +    it('should allow a conversation to be created', () => {
Fat arrow functions are discouraged when using `mocha` as it destroys mocha's `this` context. Instead, all tests should use `function(){}`

2019-09-04 05:27 UTC, closed without merging