Move account related methods from singleton to Account class
Vonage/vonage-node-sdk pull request #172
Opened 2017-12-15 16:06 UTC by mheap

There's a ton of test refactoring in here too. It's added a new set of Chai matchers (NexmoChai), a single place to configure Chai (NexmoTestUtils) and a place to configure repetative configs e.g. Credentials.

2017-12-19 13:04 UTC, AlexLakatos requested changes
LGTM 👨‍🎤 
The only thing I'm not really happy about is having the paths in the methods directly. Having a property on the class that you can then pass to the method would make it easier to update when the API changes, something like the CallResource: https://github.com/Nexmo/nexmo-node/blob/master/src/CallsResource.js#L14

2017-12-19 13:10 UTC, mheap commented
I'm not convinced on the property method myself. There aren't enough endpoints + they don't change frequently enough to warrant the extra layer of indirection for someone reading the code IMO

2017-12-19 13:48 UTC, leggetter reviewed
"accounts/settings" is used around 6 times (class and tests) so it may be nice to make this accessible via `Account.SETTINGS_PATH`. If we did that we'd likely also want to shift the pricing one.

But it's not a deal breaker.

2017-12-19 13:48 UTC, leggetter commented on src/HttpClient.js
> +    if (!callback) {
Note: I think this is internal only, but just wanted to flag in case anything was using this and passing `null` or `{}` for the params.

2017-12-19 13:48 UTC, leggetter commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
Due to this change, I think we should make it a major version bump.

2017-12-19 13:55 UTC, mheap commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
There shouldn't be any public API change due to this. It's still accessible as `nexmo.account.changePassword()`

2017-12-19 13:57 UTC, mheap commented on src/HttpClient.js
> +    if (!callback) {
If someone passes `null` or `{}` for params, it'll behave the same way. What issue do you see?

2017-12-19 14:29 UTC, leggetter commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
Yes, it's accessible via: 

```js
const Nexmo = require('nexmo');
const nexmo = new Nexmo(...);

nexmo.account.changePassword()
```

But it used to be accessible via the singleton:

```js
const nexmo = require('nexmo/lib/index.js')

nexmo.initialize(...);

nexmo.changePassword()
```

That (and others) have been removed so any code that does this (for whatever reason) would now break.

My feeling is that to be safe we should consider a major bump once we move everything out of the singleton.

2017-12-19 14:34 UTC, mheap commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
Ah ok, I didn't realise `nexmo.changePassword()` was valid (although it was possible). We can bump the major version for this

2017-12-19 14:37 UTC, leggetter commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
Yeah, anything exported from `index.js` is potentially accessible via the API.

2017-12-19 15:27 UTC, AlexLakatos commented on src/Account.js
>      this._nexmo.changePassword.apply(this._nexmo, arguments);
shouldn't this be deleted as well?

2017-12-19 15:30 UTC, AlexLakatos commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
Maybe we should keep `index.js` backwards compatible for now with `exports.methodName = account.newMethod` and just remove the exports when we're done with the singleton and do a major version bump.

2017-12-19 15:32 UTC, mheap commented on src/Account.js
>      this._nexmo.changePassword.apply(this._nexmo, arguments);
Yep, it should be

2017-12-19 15:32 UTC, mheap commented on src/index.js
> -exports.changePassword = function(newSecret, callback) {
Sounds like a sensible path

2017-12-20 16:20 UTC, mheap commented
@AlexLakatos I'm going to merge this to get the NexmoChai changes in to the main branch. We can revisit `PATH()` at DevRelWeek when we put together a plan for the library

2017-12-20 16:20 UTC, merged