Refactoring tests to es6
Vonage/vonage-node-sdk pull request #227
Opened 2018-10-26 21:55 UTC by Archaeologist03

2019-02-21 12:34 UTC, AlexLakatos commented on test/DtmfResource-test.js
> +  const httpClientStub = null;
Tests are failing because of this. You've declaring it as a `const`, but assingig `httpClientStub = sinon.createStubInstance(HttpClient);` in line 26. Making this a `let` instead should fix it.

2019-02-21 12:35 UTC, AlexLakatos requested changes
This looks good, thanks for updating your PR!

Could I also please ask you to re-base this, it looks bit messy.

2019-02-21 13:49 UTC, Archaeologist03 commented
Hi, i never have used rebase/vim before, but i think, this somewhat did the job? 
Also changed const to let.
Is this good? 
ps. Thanks for the patience. :)

2019-02-21 14:49 UTC, AlexLakatos commented on test/DtmfResource-test.js
> +  const dtmf = null;
this is causing the tests to fail, it's a `const` but it's being assigned to on line 38.

2019-02-21 14:50 UTC, AlexLakatos commented
The tests are still failing, there is a new issue in the same file with a different variable. 

Can you please run the tests locally with `npm run test`, it's going to be easier to spot the errors before it goes to travis-ci.

2020-07-20 20:17 UTC, kellyjandrews commented
This PR is really outdated now - closing for now.

2020-07-20 20:17 UTC, closed without merging