- Added extra param to Channel and Dispatch
Vonage/vonage-node-sdk pull request #234
Opened 2018-12-19 17:52 UTC by fauna5

- Added extra param to Channel and Dispatch  opts = {useBasicAuth: true}
- Added param to HttpClient.post() to allow BasicAuth

Sample api usage:
```
const Nexmo = require('nexmo');

const nexmo = new Nexmo({
  apiKey: 'key,
  apiSecret: 'secret',
});

const message = {
  content: {
    type: 'text',
    text: 'Hello from Nexmo',
  },
};

nexmo.channel.send(
  { type: 'sms', number: '01234567890' },
  { type: 'sms', number: 'Nexmo' },
  message,
  (err, data) => { console.log(data.message_uuid); },
  {useBasicAuth: true}
);
```

The one problem with this solution is that if you want to use `util.promisify` to call the API using a promise wrapper it wont work as the last arg is not the callback. However i prefer this option rather than the alternatives:
- breaking everyone using the API by rearranging params
- having a `sendWithBasicAuth` method

2018-12-19 17:59 UTC, mheap requested changes

2018-12-19 17:59 UTC, mheap commented on src/HttpClient.js
> +  post(path, params, callback, useJwt, useBasicAuth, headers = {}) {
This will break other endpoints that use `HttpClient.post` as the parameter order has changed

2018-12-20 11:06 UTC, fauna5 commented on src/HttpClient.js
> +  post(path, params, callback, useJwt, useBasicAuth, headers = {}) {
@mheap no other endpoints use the post( method. It is documented in the README but the `headers` parameter is not mentioned. I think it's safe to modify this internal API.

![image](https://user-images.githubusercontent.com/853893/50281380-2fa45a00-0447-11e9-8cf9-b31be3ba7175.png)

2018-12-21 10:14 UTC, AlexLakatos commented
Can you change the PR to be against beta-olympus please and rebase? The beta branch gets force overridden from beta-stitch and beta-olympus every time we release.

2018-12-21 10:15 UTC, AlexLakatos commented on src/HttpClient.js
> +  post(path, params, callback, useJwt, useBasicAuth, headers = {}) {
Can you please update the Readme as well with the correct signature?

2018-12-21 20:18 UTC, mheap approved these changes

2018-12-21 20:19 UTC, merged