Conversations API Updates
Vonage/vonage-node-sdk pull request #271
Opened 2019-10-18 01:51 UTC by AlexLakatos

- add beta2 API version for list endpoints
- add v1 API version for record endpoint
- add the ability to change hosts for the Conversations API

2019-10-23 02:05 UTC, dragonmantank requested changes
Couple of minor things, otherwise I think this looks good.

2019-10-23 02:05 UTC, dragonmantank commented on README.md
> +nexmo.users.next(users_list_response, callback);
This should probably match the other examples and use `response` instead of `users_list_response`, for consistency.

2019-10-23 02:05 UTC, dragonmantank commented on README.md
> +nexmo.users.next(conversations_list_response, callback);
Same here, with the change to `response` instead of `conversations_list_response`

2019-10-23 02:05 UTC, dragonmantank commented on examples/ex-record-conversation.js
> +    event_url: ["https://example.com/event"],
Is this correct? The spec looks like it's a string, not an array:

https://github.com/Nexmo/api-specification/blob/1654e87ac02f96fec928ec7c7dcb1729638bd3eb/definitions/conversation.yml#L693

2019-10-23 02:05 UTC, dragonmantank commented on examples/run-examples.js
> +  'ex-create-conversation.js',
Should this be commented out as well?

2019-10-25 16:29 UTC, mheap commented on examples/ex-record-conversation.js
> +    event_url: ["https://example.com/event"],
The spec is wrong in this case. `event_url` should always be an array of strings (and I've checked, you get a `400` if it's not)

2019-10-25 16:29 UTC, mheap commented on examples/run-examples.js
> +  'ex-create-conversation.js',
It's fine to leave this uncommented. This is a development file and the uncommented line is usually the last thing we tested

2019-10-25 16:37 UTC, merged