Add steps for running code from an open PR
Vonage/vonage-node-sdk pull request #281
Opened 2019-12-02 08:43 UTC by AlexLakatos

2019-12-02 08:54 UTC, tbedford requested changes
Minor suggestions.

2019-12-02 08:54 UTC, tbedford commented on CONTRIBUTING.md
> +5. Update `examples/run-examples.js` to uncomment the examples you want to run
5. Uncomment the appropriate line in `examples/run-examples.js` for each example you want to run.

2019-12-02 08:54 UTC, tbedford commented on CONTRIBUTING.md
> +6. Update `example.env` in the examples folder with your api key and secret, and rename it to be `.env`
6. In the `examples` folder, copy `example.env` to `.env` and update it with your API key and API secret.

2019-12-03 05:36 UTC, AlexLakatos commented
@tbedford thanks for the suggestions, I've incorporated them in the PR.

2019-12-03 09:26 UTC, tbedford approved these changes

2019-12-03 09:26 UTC, merged