add some typings for message api
Vonage/vonage-node-sdk pull request #290
Opened 2020-03-02 05:02 UTC by jin60641

It will support Message API's sendSms method

reference
[MessageRequestResponseStatusCode](https://developer.nexmo.com/messaging/sms/guides/troubleshooting-sms)
[MessageRequestResponseSuccess, MessageError, MessageRequestResponse, SendSmsOptions, SendSms, Message](https://developer.nexmo.com/api/sms)

2020-03-02 09:39 UTC, AlexLakatos commented
Messages API is only supported on the beta branch for now, so I'll switch this on the beta branch for now.

2020-03-02 09:43 UTC, AlexLakatos commented
@jin60641 this breaks backwards compatibility for Verify. Can you please switch back the Verify responses and add a TODO note to change them when we release a new major version?

2020-03-02 09:44 UTC, AlexLakatos requested changes
Switch back the Verify namespacing.

2020-03-03 09:54 UTC, jin60641 commented
> @jin60641 this breaks backwards compatibility for Verify. Can you please switch back the Verify responses and add a TODO note to change them when we release a new major version?

I switch back the Verify api's namesapcing and add TODO comment on top of file.
Thanks

2020-06-02 12:52 UTC, Abhi347 commented on typings/index.d.ts
> +    export enum MessageRequestResponseStatusCode {
The status codes are returned as string, not integers. You should change the codes to string.

2020-07-11 16:45 UTC, Coooi commented
Any updates on this?
I really looking forward to it.

2020-07-20 20:20 UTC, kellyjandrews commented
I will evaluate this later this week along with #299 and get these added in.  Thanks for your patience.

2020-07-22 09:24 UTC, jin60641 commented on typings/index.d.ts
> +    export enum MessageRequestResponseStatusCode {
I pushed a new commit. check please.

2020-07-23 22:28 UTC, merged

2020-07-23 22:30 UTC, kellyjandrews commented
I pulled these in for now and will start a larger change for v2.9.  Thanks for the contribution.  

If you want to help out with others, I will be creating a new branch `typing-updates` to work towards a more complete set of types.