Add PSD2 Support for Verify
Vonage/vonage-node-sdk pull request #305
Opened 2020-06-11 13:30 UTC by AlexLakatos

This PR adds `nexmo.verify.psd2` as a method, and updates all the necessary files for release.

To run it:
- switch to the `psd2` branch
- `npm compile`
- uncomment the added examples in `run-examples.js`
- `node run-examples.js`

Note: you can't run both examples at the same time, Verify won't let you run concurrent verifications on the same number. So each at a time. If you don't want to wait 5 minutes and receive an SMS and 2 phone calls in the process, uncomment the `check-verify` example, and run it with the code you got from psd2.

2020-06-12 18:04 UTC, slorello89 requested changes
Ran everything and it looked good - just a minor doc item and this should be a minor release. Killer last contribution from @AlexLakatos

2020-06-12 18:04 UTC, slorello89 commented on src/Verify.js
> +   * TODO: document
Needs Summary docs

2020-06-12 18:04 UTC, slorello89 commented on package.json
> +  "version": "2.7.1",
This is a new feature - thus it should be a new minor release

2020-06-12 18:04 UTC, slorello89 commented on CHANGELOG.md
> +## 2.7.1
should be 2.8.0

2020-06-15 13:09 UTC, lornajane commented on CHANGELOG.md
> +## 2.7.1
Why should it be 2.8.0? It's a minor, non-breaking additional change so a patch seems OK to me. If we can clarify, I'll review and try to merge/release

2020-06-15 13:25 UTC, slorello89 commented on CHANGELOG.md
> +## 2.7.1
As this is a minor non-breaking new feature that we're adding - it would be appropriate to increment the minor version. This is my understanding from [semver](https://semver.org/)

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
```

2020-06-24 09:59 UTC, lornajane commented on src/Verify.js
> +   * TODO: document
Nothing else has this so not a blocker for now IMO.

2020-06-24 10:09 UTC, lornajane commented on package.json
> +  "version": "2.7.1",
Updated

2020-06-24 10:09 UTC, lornajane commented on CHANGELOG.md
> +## 2.7.1
Thanks! I've switched it to 2.8.0

2020-06-24 12:41 UTC, slorello89 approved these changes
LGTM

2020-06-26 09:10 UTC, merged