Rebrand updates
Vonage/vonage-node-sdk pull request #325
Opened 2020-09-03 17:04 UTC by kellyjandrews

Changes for moving from Nexmo to Vonage namespace.

2020-09-04 18:51 UTC, slorello89 requested changes
Some questions about the contributor's guide, some emails are pointing at support@vonage.com (which I don't think actually route correctly yet). Looks like there as a problem with a find/replace that removed some important spaces.

2020-09-04 18:51 UTC, slorello89 commented on CONTRIBUTING.md
> +1. `git checkout BRANCH_NAME`
`git checkout -b BRANCH_NAME` unless the branch already exists

2020-09-04 18:51 UTC, slorello89 commented on CONTRIBUTING.md
> +1. `npm compile`
npm complains that `compile` isn't an npm command

2020-09-04 18:51 UTC, slorello89 commented on CONTRIBUTING.md
> +1. Download the `https://github.com/Vonage/vonage-node-code-snippets` repository
maybe have contributors download the snippets into a separate directory. If you're contributing you probably don't want to have the snippets in the same directory as the repo you're contributing to as they may accidentally get picked up in commits and cause a git pita that might be discouraging

2020-09-04 18:51 UTC, slorello89 commented on CONTRIBUTING.md
> +1. `npm compile`
is this supposed to be `npm run compile`?

2020-09-04 18:51 UTC, slorello89 commented on CONTRIBUTING.md
> +1. `npm install`
should be a numbered list:

1. 
2. 
3. 
4. 

etc. . .

2020-09-04 18:51 UTC, slorello89 commented on src/CallsResource.js
> +   * @param {Credentials} creds - Credentials used when interacting with the VonageAPI.
Here and in a bunch of places `VonageAPI` should be `Vonage API`

2020-09-04 18:51 UTC, slorello89 commented on src/Credentials.js
> + * @param {string} [signatureSecret] - A Vonagesignature Secret
Looks like there was a find and replace issue where "Nexmo " was replaced with "Vonage"

2020-09-04 18:51 UTC, slorello89 commented on src/DtmfResource.js
> +   * @param {Credentials} creds - Credentials used when interacting with the VonageAPI.
find and replace issue here as well

2020-09-04 18:51 UTC, slorello89 commented on src/HttpClient.js
> +          "This endpoint may need activating on your account. Please email support@vonage.com for more information";
support@nexmo.com is still the correct email.

2020-09-04 18:51 UTC, slorello89 commented on src/HttpClient.js
> +      // Fix broken due ot 411 Content-Length error now sent by VonageAPI
missing space

2020-09-04 18:51 UTC, slorello89 commented on src/FilesResource.js
> +   * @param {Credentials} creds - Credentials used when interacting with the VonageAPI.
missing space

2020-09-04 18:51 UTC, slorello89 commented on src/NumberInsight.js
> +   *                 Tells the Vonageplatform to make callbacks as soon as an
missing space

2020-09-04 18:51 UTC, slorello89 commented on src/StreamResource.js
> +   * @param {Credentials} creds - Credentials used when interacting with the VonageAPI.
missing space

2020-09-04 18:51 UTC, slorello89 commented on src/TalkResource.js
> +   * @param {Credentials} creds - Credentials used when interacting with the VonageAPI.
missing space

2020-09-04 18:51 UTC, slorello89 commented on src/Vonage.js
> +    let userAgent = "@vonage/server-sdk/UNKNOWN node/UNKNOWN";
is there a way to set the `UNKNOWN`s to the correct sdk/language version? or am I just missing obvious?

2020-09-04 18:51 UTC, slorello89 commented on test/Conversion-test.js
> +          "This endpoint may need activating on your account. Please email support@vonage.com for more information"
support email is still `support@nexmo.com`

2020-09-04 19:47 UTC, kellyjandrews commented on CONTRIBUTING.md
> +1. `npm install`
It already is ;)

2020-09-04 19:47 UTC, kellyjandrews commented on CONTRIBUTING.md
> +1. Download the `https://github.com/Vonage/vonage-node-code-snippets` repository
That was the sentiment - I'll be more explicit

2020-09-04 19:47 UTC, kellyjandrews commented on src/Vonage.js
> +    let userAgent = "@vonage/server-sdk/UNKNOWN node/UNKNOWN";
That's how it was when I got it - I have no idea why it's like that, but not changing it here

2020-09-04 19:47 UTC, kellyjandrews commented on CONTRIBUTING.md
> +1. `git checkout BRANCH_NAME`
Since this is specifically for a PR, wouldn't it already exist?

2020-09-04 19:48 UTC, kellyjandrews commented
Ok @slorello89 thanks for catching those :). Should be a bit better now.

2020-09-08 19:02 UTC, superdiana reviewed
LGTM

2020-09-08 19:34 UTC, merged