Fix types module name
Vonage/vonage-node-sdk pull request #355
Opened 2020-09-30 14:59 UTC by kellyjandrews

## Description
Updated `vonage` to `@vonage/server-sdk` and `NexmoApiError` to `VonageApiError`

## Motivation and Context
Fixes #354 

## Testing Details
No changes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-09-30 18:59 UTC, dragonmantank requested changes
Module name change looks fine, just a question on the interface name change

2020-09-30 18:59 UTC, dragonmantank commented on typings/index.d.ts
> +    export interface VonageApiError {
Do we need to change any internal references from `NexmoApiError` to `VonageApiError` as well?

2020-09-30 20:38 UTC, kellyjandrews commented on typings/index.d.ts
> +    export interface VonageApiError {
I believe all other references were changed.

2020-10-02 16:17 UTC, dragonmantank approved these changes
LGTM :+1:

2020-10-05 12:25 UTC, merged