Added typings for AccountApi
Vonage/vonage-node-sdk pull request #372
Opened 2020-10-05 14:03 UTC by bpedersen

Added typings to AccountAPI

## Description
Added typings for the AccountAPI from what I could find online

## Motivation and Context
Hacktoberfest (https://developer.nexmo.com/hacktoberfest)
This was requested by https://github.com/Vonage/vonage-node-sdk/issues/359

## Testing Details
No tests should be affected

## Example Output or Screenshots (if appropriate)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-05 14:35 UTC, kellyjandrews commented
Thanks for the contribution - we will get it reviewed and merged as soon as we can!

2020-10-07 13:41 UTC, bpedersen commented
Thank you for the Hacktoberfest tag, however it looks like they changed the requirements recently. 
Looks like we need to use a tag for PRs as Hacktoberfest-Accepted
https://hacktoberfest.digitalocean.com/hacktoberfest-update

2020-10-07 13:57 UTC, mheap commented
Good news! The `vonage-node-sdk` repo has the `hacktoberfest` topic, so all PRs submitted against this repo are implicitly eligible to be counted

2020-10-12 13:55 UTC, kellyjandrews requested changes
Looks like this is pretty close - just add the account module to the Vonage export and it should be good to go.

2020-10-12 13:55 UTC, kellyjandrews commented on typings/index.d.ts
> +		public readonly message: Message;
You will also need to add the account type to the default export here.

2020-10-27 14:29 UTC, garann commented
> Thank you for the Hacktoberfest tag, however it looks like they changed the requirements recently.
> Looks like we need to use a tag for PRs as Hacktoberfest-Accepted
> https://hacktoberfest.digitalocean.com/hacktoberfest-update

Hi @bpedersen, just checking on this PR and https://github.com/Vonage/vonage-node-sdk/pull/374. I see both have changes requested, and once those are made it should be possible to get them accepted and merged. Are you still hoping to get these accepted before the end of the month? Thank you!

2021-03-11 15:54 UTC, closed without merging