Added typings for ApplicationAPI
Vonage/vonage-node-sdk pull request #374
Opened 2020-10-06 14:00 UTC by bpedersen

Added typings to ApplicationAPI

## Description
Added typings for the ApplicationAPI from what I could find online

## Motivation and Context
Hacktoberfest (https://developer.nexmo.com/hacktoberfest)
This was requested by https://github.com/Vonage/vonage-node-sdk/issues/360

## Testing Details
No tests should be affected

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-07 13:41 UTC, bpedersen commented
Thank you for the Hacktoberfest tag, however it looks like they changed the requirements recently.
Looks like we need to use a tag for PRs as Hacktoberfest-Accepted
https://hacktoberfest.digitalocean.com/hacktoberfest-update

2020-10-07 13:57 UTC, mheap commented
Good news! The `vonage-node-sdk` repo has the `hacktoberfest` topic, so all PRs submitted against this repo are implicitly eligible to be counted

2020-10-12 14:02 UTC, kellyjandrews requested changes

2020-10-12 14:02 UTC, kellyjandrews commented on typings/index.d.ts
> +	export interface AppCapabilities {
I think this section is missing a few items - looks like you would need voice, rtc, messages, and vbc as high level objects. Check this section of the API docs - https://developer.nexmo.com/api/application.v2#createApplication

2020-10-12 14:02 UTC, kellyjandrews commented on typings/index.d.ts
> +	}
You will need to export the interface like Verify and Message here.

2021-03-11 15:54 UTC, closed without merging