Added typings for VoiceAPI#364
Vonage/vonage-node-sdk pull request #379
Opened 2020-10-08 02:56 UTC by PeppermintNDaisies

# :sparkles: Added new typings matching the voice API

## Description
Added a voice API section at the end of typings/index.d.ts in which the typings for Voice API were added, following as much as possible code style inside the file in which the changes were made. A total of 16 interfaces and 1 class were added, nothing (code that was already there) was changed. 

## Motivation and Context
This solves issue #364 

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-12 14:28 UTC, kellyjandrews requested changes
It looks like I may have given some bad instructions.  The PR looks great and matches the docs, however the typings won't line up with the SDK - https://github.com/Vonage/vonage-node-sdk/blob/master/src/Voice.js

If you could adjust the interfaces to match the SDK, and use the docs as a reference for types, I think we have it. Thanks!

2020-10-12 14:28 UTC, kellyjandrews commented on typings/index.d.ts
> +        To_id?: string;
Since these are updates to the messages interface, move the above changes into a separate PR. Thanks!

2020-10-12 14:28 UTC, kellyjandrews commented on typings/index.d.ts
>      export default class Vonage {
Voice class will need to be exported in the default class as well.

2020-10-12 14:56 UTC, PeppermintNDaisies commented
> It looks like I may have given some bad instructions. The PR looks great and matches the docs, however the typings won't line up with the SDK - https://github.com/Vonage/vonage-node-sdk/blob/master/src/Voice.js
> 
> If you could adjust the interfaces to match the SDK, and use the docs as a reference for types, I think we have it. Thanks!

Oh I'm so sorry I missed that part!  ABsolutely, I will fix it and make it match with the SDK!

2020-10-12 15:01 UTC, kellyjandrews commented
There are a couple of recently closed PRs with typings done very well - you can check those as an example, and _always_ feel free to ask questions.

2020-10-29 14:10 UTC, kellyjandrews approved these changes
These look great - thanks for getting it ready to go.

2020-10-29 14:22 UTC, PeppermintNDaisies commented
> These look great - thanks for getting it ready to go.

Really?  Amazing! I did some changes but still didn't know if they were okay, but completely forgot to ask you to review it, I'm glad this PR got approved!

2020-10-29 14:23 UTC, kellyjandrews commented
@PeppermintNDaisies I just realized there are some conflicts that need to be resolved.  If you could get those fixed up, I'll get it merged in. The changes look fine - just need to get it up to date with master.

2020-10-29 14:29 UTC, PeppermintNDaisies commented
> @PeppermintNDaisies I just realized there are some conflicts that need to be resolved. If you could get those fixed up, I'll get it merged in. The changes look fine - just need to get it up to date with master.

Got it!

2020-10-30 02:49 UTC, PeppermintNDaisies commented
@kellyjandrews Merge conflicts solved!

2020-11-02 19:46 UTC, kellyjandrews approved these changes

2020-11-02 19:46 UTC, merged