Beta base
Vonage/vonage-node-sdk pull request #408
Opened 2020-11-18 13:18 UTC by kellyjandrews

## Description
This pull requests updates the beta branch to match the current changes in master. 

## Motivation and Context
Resolves the beta branch for the brand changes.

## Testing Details
All tests pass, and have been updated to reflect new branding.

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-11-20 15:35 UTC, dragonmantank requested changes
Couple of minor things pop out just giving this a once over. Mostly everything looks fine since it's all name swapping, but didn't run any of the code. Was just looking for obvious things.

2020-11-20 15:35 UTC, dragonmantank commented on CODE_OF_CONDUCT.md
> +<<<<<<< HEAD
Conflict markers got merged

2020-11-20 15:35 UTC, dragonmantank commented on src/Dispatch.js
> +    this._vonage = this.options.vonageOverride || vonage;
Does this need removed from here like with the other modules?

This is a rebranding branch, but might be good to flag as an additional change if needed.

2020-11-20 15:35 UTC, dragonmantank commented on test/HttpClient-test.js
> +    var expectedUserAgent = "vonage-node/1.0.0/v4.4.7";
Should have this match the actual user agent string to be safe

2020-11-20 15:40 UTC, kellyjandrews commented on src/Dispatch.js
> +    this._vonage = this.options.vonageOverride || vonage;
So this is something new in the beta branch that I've not seen elsewhere, but it's baked into tests.  I don't think it was removed from the other modules, but actually added to these.

2020-11-24 18:26 UTC, dragonmantank approved these changes
Looks good to me :+1:

2020-11-24 18:27 UTC, merged