Replace NI Advanced call with synchronous version
Vonage/vonage-node-sdk pull request #66
Opened 2016-09-29 15:45 UTC by cbetta

* Moved async call into own option
* Fixed all API endpoints to ones used in current docs
* Updated documentation to highlight changes

This will probably require a minor release bump as this commit will break for anyone expecting `nexmo.numberInsight.get({level: 'advanced'})` to be asynchronous.

This will probably require a minor release bump as this commit will break for anyone expecting `nexmo.numberInsight.get({level: 'advanced'})` to be asynchronous.

Closes #64

2016-09-29 16:02 UTC, leggetter requested changes
There seem to be quite a few whitespaces changes in the code. Not sure why that is, and I'm not going to get to worried about it :)

Main thing is that the README seems to have been broken. I think a bunch of text may have accidentally been removed.

2016-09-29 16:02 UTC, leggetter commented on src/index.js
> +var niBasicEndpoint = {host:'api.nexmo.com',path:'/ni/advanced/async/json'};
The variable name and `path` value don't seem to match up.

2016-09-29 16:02 UTC, leggetter commented on src/NumberInsight.js
> +      console.log('3');
Debug left in.

2016-09-29 16:02 UTC, leggetter commented on src/NumberInsight.js
> +      console.log('4');
Debug left in.

2016-09-29 16:02 UTC, leggetter commented on README.md
> +=======
Is this required? The `###` should be enough and I think all other headers use this syntax.

2016-09-29 16:02 UTC, leggetter commented on README.md
> +=======
Required?

2016-09-29 16:02 UTC, leggetter commented on README.md
> +=======
I'm not sure why this seems to be followed by code. Maybe the GitHub preview has gone wonky?

I see:

```
### Cancel Number
======

nexmo.numberInsight.get({level: 'advanced', number: NUMBER}, consolelog);
\```

For more info...
```

(ignore the backslash)

2016-09-29 16:03 UTC, leggetter commented on README.md
> +=======
I think this is where a mistake has been made and text accidentally removed.

2016-09-29 16:11 UTC, cbetta commented
@leggetter Damn, that's not right. Seems my rebase didn't go well. I'll have a look

2016-09-29 18:12 UTC, leggetter reviewed
I'd suggest we stick with the consistent snakeCase naming convention of variables. I can live with the whitespace changes :)

2016-09-29 18:12 UTC, leggetter commented on README.md
> +nexmo.numberInsight.get({level: 'advanced', number: NUMBER}, callback_function);
`callback_function` -> `callback` - Looks like your rubyism has snuck in!

2016-09-29 18:12 UTC, leggetter commented on README.md
> +nexmo.numberInsight.get({level: 'advancedAsync', number: NUMBER, callback: "http://example.com"}, callback_function);
just `callback` is cool

2016-09-29 18:17 UTC, cbetta commented on README.md
> +nexmo.numberInsight.get({level: 'advanced', number: NUMBER}, callback_function);
@leggetter haha, sorry. Was just trying to clarify here there's a difference in the Async call between the callback URL for the webhook and the callback function for this function.

Want me to change it to `callbackFunction`?

Additionally we should add this to the linter to make sure we ensure camelCase.

2016-09-29 18:17 UTC, cbetta commented on README.md
> +nexmo.numberInsight.get({level: 'advancedAsync', number: NUMBER, callback: "http://example.com"}, callback_function);
See other comment

2016-09-29 18:29 UTC, leggetter commented on README.md
> +nexmo.numberInsight.get({level: 'advanced', number: NUMBER}, callback_function);
nah - just use `callback`. All/most of the other examples just use that.

2016-09-29 18:31 UTC, cbetta commented on README.md
> +=======
Renamed it to `callback` everywhere

2016-09-29 18:39 UTC, cbetta commented on README.md
> +nexmo.numberInsight.get({level: 'advanced', number: NUMBER}, callback_function);
@leggetter fixed. And updated all other mentions to callback too instead of `consolelog` which seems to not be used anywhere else.

2016-09-29 20:14 UTC, leggetter approved these changes

2016-09-29 20:15 UTC, merged

2016-09-29 20:16 UTC, leggetter commented
@cbetta - so, now a version bump and the need to publish?

@tjlytle - worth your input on the decision we make for the version. There's a breaking change here with one of the APIs since insight advanced used to be async. It's now sync. There's a specific async version now.

2016-09-29 20:23 UTC, tjlytle commented
@leggetter @cbetta Any way to keep the existing behaviour in _this_ version and change in a future major release? `advancedSync` would be the new `level`.

2016-09-29 21:38 UTC, cbetta commented
@leggetter @tjlytle I'd say bump it to `1.1.0`. This is what semver is for.

2016-09-29 21:44 UTC, leggetter commented
If it's a breaking API change then in theory we should be changing the MAJOR. So that's 2.0.0.

2016-09-29 21:46 UTC, cbetta commented
Ah I stand corrected. Yeah so technically 2.0.0. I'm happy with that. Embrace Chrome's "don't be afraid to increase the major" motto!

Also happy to make the change minor ;)

2016-09-29 23:02 UTC, tjlytle commented
I'd rather save 2.0 for a more significant change of the library (which
will likely be sooner than later).

2016-09-30 13:36 UTC, cbetta commented
@tjlytle although I understand your intent I also want to point out that that's a completely cosmetic decision. Version numbers are meant to signify change in a semantic way, not to celebrate some milestone in the code base. 

Anyway, don't want to be a blocker so I'm happy to change the API to `advanced` and `advancedSync` to keep the code backwards compatible. @leggetter thoughts?