docs: move markdown files to github
Vonage/vonage-node-sdk pull request #721
Opened 2022-11-10 18:54 UTC by manchuck

Removed Make file and duplication COC, Contributing and License files. It helps keep the root cleaner and prevents the duplication of these files

2022-11-17 03:39 UTC, dragonmantank requested changes
Need to clean up the maintenance stuff

Not sure we should move these files to `.github/` ... convention is to generally keep these things in the root of the project, and leave `.github/` to files that are specific only to GitHub functionality. 

While not a blocker, I would prefer to keep a `MAINTENANCE.md` file separate from contributing, as contributors only need to worry about how to submit PRs.

2022-11-17 03:39 UTC, dragonmantank commented on .github/CONTRIBUTING.md
> +* New commits are pushed to their own feature branch and merged into `master`.
Need to rework this, as this isn't how we actually release, and the branch names need corrected.

2022-11-17 21:23 UTC, manchuck commented on .github/CONTRIBUTING.md
> +* New commits are pushed to their own feature branch and merged into `master`.
Ok let us chat about this a bit more when we want to make the 3.x the main branch

2022-11-18 13:26 UTC, manchuck commented
@dragonmantank moving everything to `.github` makes packaging easer, as we can ignore everything in that directory. Another reason is that we had some of the docs copied into the packages which could cause confusion

2022-11-18 14:40 UTC, dragonmantank commented
I'd prefer we keep the main docs in the root, as that is where people expect them. I don't mind removing the duplicates from the sub-packages as we can link to them the READMEs, but we shouldn't push the files off to somewhere else. None of the root stuff is pulled into the packages anyway.

2022-11-21 15:57 UTC, dragonmantank approved these changes

2022-11-21 15:57 UTC, merged