docs: sms migration guide
Vonage/vonage-node-sdk pull request #725
Opened 2022-11-10 20:14 UTC by manchuck

## Description
SMS migration docs

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-17 03:32 UTC, dragonmantank requested changes
Couple of typos and need a valid example

2022-11-17 03:32 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +If you are using the main Vonage Node Server SDK, you will need to configure it using a Vonage API Key and Secret. The setup is the same for any other key/secret-based application. The applications c
```suggestion
If you are using the main Vonage Node Server SDK, you will need to configure it using a Vonage API Key and Secret. The setup is the same for any other key/secret-based application. The SMS client will then be available as `vonage.sms`.
```

2022-11-17 03:32 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +vonage.sms.listCountryPricing()
Should be an example to send an SMS

2022-11-17 03:32 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +    applicationId: APP_ID,
This should be a key/secret auth instead

2022-11-17 03:32 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +This module is also capable of working as a standalone module. The only difference is that you create an `Applications` object and pass the credentials there.
```suggestion
This module is also capable of working as a standalone module. The only difference is that you create a `SMS` object and pass the credentials there.
```

2022-11-17 03:32 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +| `vonage.sms.searchREjections()` | _Removed_ |  This has been removed |
```suggestion
| `vonage.sms.searchRejections()` | _Removed_ |  This has been removed |
```

2022-11-18 01:09 UTC, dragonmantank requested changes

2022-11-18 01:09 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +vonage.sms.({
This is missing the method name :P

2022-11-18 01:09 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +The package name has changed and is now a companion to the core Vonage Node SDK. You can continue to use the `@vonage/server-sdk` package or now use the Numbers SDK as a standalone package. If you wo
Should say SMS and not Numbers (I think I missed this the first pass)

2022-11-21 15:05 UTC, manchuck commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +vonage.sms.({
this is what happens when you don't have your normal keyboard and muck up your vim commands

2022-11-21 15:59 UTC, dragonmantank requested changes

2022-11-21 15:59 UTC, dragonmantank commented on packages/sms/v2_TO_v3_MIGRATION_GUIDE.md
> +    apKey: API_KEY,
```suggestion
    apiKey: API_KEY,
```

2022-11-21 16:02 UTC, dragonmantank approved these changes

2022-11-21 16:02 UTC, merged