fix: Correct our return types when sending SMS
Vonage/vonage-node-sdk pull request #743
Opened 2022-11-26 03:17 UTC by dragonmantank

## Description

Corrects the type definition for the returned SMS responses to match the original declaration. This also adds keys with appropriate deprecation notices to not break existing code. 

## Motivation and Context

Per #742 , the definitions we provided for the return response did not match the API. Looks like as this was an early module, we never finished cleaning up to make it match.

## Testing Details

Unit tests

## Example Output or Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-28 16:22 UTC, manchuck requested changes
Just update the test

2022-11-28 16:22 UTC, manchuck commented on packages/sms/__tests__/sms.test.ts
> +        expect(results.messageCount).toEqual(1)
This test should be done using `test.each`. Otherwise, we call the `expects` conditionally if `results.messages.length` is empty. This could happen with a bad mock

2022-11-29 15:49 UTC, dragonmantank commented on packages/sms/__tests__/sms.test.ts
> +        expect(results.messageCount).toEqual(1)
You'd never have a `results.messages.length` < 1, because it's a list of the messages that were sent. A length of 0 would indicate we somehow sent nothing, but were still successful. The above test isn't testing different use cases, all the `expects()` are a single valid response being returned, and testing each property (mostly for backward compatibility)

2022-11-29 17:37 UTC, manchuck approved these changes
Let's go with it for now, and when we add in the linter rules, we can most likely make it an exception if it bugs out

2022-11-30 15:58 UTC, merged