docs: adding sms readme
Vonage/vonage-node-sdk pull request #765
Opened 2022-12-08 22:25 UTC by manchuck

## Description
adding sms readme

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-12-09 21:01 UTC, dragonmantank requested changes

2022-12-09 21:01 UTC, dragonmantank commented on packages/sms/README.md
> +### With Yarn
We should either add yarn to each Readme, or remove it from here

2022-12-09 21:01 UTC, dragonmantank commented on packages/sms/README.md
> +const { Vonage, Auth } = require('@vonage/server-sdk');
We don't expose Auth here

2022-12-12 15:53 UTC, manchuck commented on packages/sms/README.md
> +### With Yarn
We should have it in each readme. Is there one that is missing?

2022-12-13 18:44 UTC, dragonmantank commented on packages/sms/README.md
> +### With Yarn
For some reason it only stood out here us having it. I don't know why.

2022-12-13 18:45 UTC, dragonmantank approved these changes

2022-12-13 20:02 UTC, merged