fix(types): verify response types
Vonage/vonage-node-sdk pull request #794
Opened 2023-02-21 21:16 UTC by manchuck

This fixes the typescript interfaces and types for the verify module

## Description

I noticed some other issues with some of the types being returned as well as the requests being passed into the verify module. I have addressed them all and updated the tests 

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-24 18:15 UTC, dragonmantank requested changes

2023-02-24 18:15 UTC, dragonmantank commented on packages/verify/lib/classes/PSD2.ts
> +  language?: string;
We should mark this as deprecated, and will still need to take this into account when serializing down to a JSON blob

2023-02-24 18:15 UTC, dragonmantank commented on packages/verify/lib/classes/PSD2.ts
> +      this.lg = language;
We should still set `this.language` for the time being as well

2023-02-24 18:15 UTC, dragonmantank commented on packages/verify/lib/classes/Verification.ts
> +  lg?: VerifyLanguages;
We should keep `language` for BC and mark it as deprecated

2023-02-24 18:15 UTC, dragonmantank commented on packages/verify/lib/classes/Verification.ts
> +      this.lg = language;
Same as PSD2, should also set `this.language` for the time being

2023-02-24 18:15 UTC, dragonmantank commented on packages/verify/lib/enums/Workflows.ts
> +    TMS = '7',
This should be `TTS`

2023-02-24 18:15 UTC, dragonmantank commented on packages/verify/lib/verify.ts
> +    const resp = await this.sendPostRequest<
This is probably going to be in a few different places, but for consistency I think we should actually throw an Error instead of returning an error. This is more consistent with the newer APIs work, and much easier to find and handle than returning an error.

That would be a BC break, so I would document that behavior change, or make it forward compatible with an options flag that will allow you to keep existing behavior or throw an error (thereby deprecating the old behavior and allowing the user a way to opt-in to new behavior to make upgrading easier). 

Just because the API is bad and doesn't return proper HTTP codes doesn't mean the SDK shouldn't behave as expected.

2023-02-24 18:46 UTC, manchuck commented on packages/verify/lib/verify.ts
> +    const resp = await this.sendPostRequest<
I want to avoid having this PR being a BC one. This was trying to address issues with the types. When we start working on verify V2, then we'll go back and have this throw an exception.

2023-02-27 15:25 UTC, dragonmantank approved these changes
LGTM

2023-02-27 15:33 UTC, merged