feat: redact module
Vonage/vonage-node-sdk pull request #798
Opened 2023-02-27 21:07 UTC by manchuck

Provides SDK access for the redact API 

## Description

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-02 19:21 UTC, dragonmantank requested changes
Pull out audit, and some minor text changes

2023-03-02 19:21 UTC, dragonmantank commented on README.md
> +| Redact API | General Availability |✅|
Redact is still Developer Preview, but we can mark it that we now support it

2023-03-02 19:21 UTC, dragonmantank commented on packages/redact/lib/interfaces/response/errorResponse.ts
> +export interface ErrorResponse {
Wouldn't hold this up, but since we try and return RFC 7807 responses like this, we could move to the vetch package maybe, so we don't have to do this every API.

Alternate argument - we don't define this and let it trickle up via Error handling instead

2023-03-02 19:21 UTC, dragonmantank commented on packages/server-sdk/README.md
> +| Redact API | General Availability |✅|
Same as before, keep this "Developer Preview"

We're only making it available via the kitchen sink because we had it in 2.x

2023-03-02 19:21 UTC, dragonmantank commented on packages/server-sdk/lib/vonage.ts
> +    this.audit = new Audit(this.credentials, this.options);
The Audit module shouldn't be brought in as it's in Beta status right now

2023-03-03 20:25 UTC, manchuck commented on packages/redact/lib/interfaces/response/errorResponse.ts
> +export interface ErrorResponse {
Yea I agree. Next time we give vetch a little TLC, we can visit

2023-03-08 14:43 UTC, dragonmantank approved these changes
Provisionally approving depending on if we need to fix the versions in the server-sdk `package.json`

2023-03-08 14:43 UTC, dragonmantank commented on packages/server-sdk/package.json
> -        "@vonage/accounts": "^1.1.2",
Do we need to rebase here? We've ended up dropping back on all these packages.

If this is going to get cleaned up before deploy we can ignore this for now.

2023-03-08 15:13 UTC, manchuck commented on packages/server-sdk/package.json
> -        "@vonage/accounts": "^1.1.2",
Yea, once this and the SMS PR gets merged in, I will clean up the packages.

2023-03-08 15:13 UTC, merged