feat: verify v2
Vonage/vonage-node-sdk pull request #805
Opened 2023-03-15 20:28 UTC by manchuck

Adding in Verify v2

## Description
This adds in the Verify V2 module 

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-16 19:21 UTC, dragonmantank requested changes
Verify v2 also supports basic header auth, so like with Messages we should support that (it's not a side effect of the auth changes, but a way for customers to still send Verify without setting up an application)

2023-03-16 19:21 UTC, dragonmantank commented on packages/verify2/lib/verify2.ts
> +  protected authType = AuthenticationType.JWT;
Verify v2 also supports basic auth headers, it just disables the callbacks

2023-03-23 18:47 UTC, manchuck commented on packages/verify2/lib/verify2.ts
> +  protected authType = AuthenticationType.JWT;
Resolved offline

2023-03-23 20:18 UTC, dragonmantank approved these changes

2023-03-23 21:46 UTC, merged