feat: users package
Vonage/vonage-node-sdk pull request #845
Opened 2023-07-26 20:09 UTC by manchuck

## Description

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-09 17:36 UTC, dragonmantank requested changes
Looks good, would change the update user method though

2023-08-09 17:36 UTC, dragonmantank commented on packages/user/lib/user.ts
> +  async updateUser(userId: string, user: UserType): Promise<UserType> {
This should just take a UserType, and bail out if they don't pass an ID as part of the object. There's never a reason to update a user without an ID, and we don't want someone passing in an ID trying to update a user object with a different ID
```suggestion
  async updateUser(user: UserType): Promise<UserType> {
```

2023-08-09 17:36 UTC, dragonmantank commented on packages/user/lib/user.ts
> +      `${this.config.apiHost}/v1/users/${userId}`,
```suggestion
      `${this.config.apiHost}/v1/users/${user.id}`,
```

2023-08-09 19:58 UTC, manchuck commented on packages/user/lib/user.ts
> +  async updateUser(userId: string, user: UserType): Promise<UserType> {
Ive been wanting to have the methods go this way but didn't because that was how the other packages had the signature this way

2023-08-14 15:08 UTC, dragonmantank approved these changes

2023-08-14 15:08 UTC, merged