docs(server-client): adding server-client docblocks
Vonage/vonage-node-sdk pull request #875
Opened 2023-10-18 20:21 UTC by manchuck

This also updated vetch as it was not providing the functionality needed. Vetch is now deprecated and only contains type definitions for server-client 

## Description

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-04 15:18 UTC, dragonmantank requested changes
Questions on access visibility and some code changes

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/enums/AuthenticationType.ts
> +     * @deprecated This method is deprecated.
This is only deprecated in certain APIs, not across-the-board

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/enums/GenericErrorCodes.ts
> +   * Multiple authentication methods were provided in the request. Multiple
duplicated lines basically

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/fileClient.ts
> +  public authType = AuthenticationType.JWT;
Should we be letting this change directly, or add a setter?

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/fileClient.ts
> +  protected saveFilePath: string = '';
Is this async-safe? For example, if I'm downloading a batch of different files

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/client.ts
> +  public authType?: AuthenticationType = AuthenticationType.QUERY_KEY_SECRET;
Not sure why we are switching these to public, the user should never be changing the authentication type by themselves

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/client.ts
> +      timeout: options?.timeout || 3000,
Not sure why we are setting this now - we should only set a value if the user explicitly adds a timeout. Otherwise, we may cut connections early for anyone taking advantage of the default behavior

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/client.ts
> +    // Regardless of the setting, set the auth params in the query string
Why this change? We shouldn't be trying to add a key/secret to the query params based on request type, we should be adding them based on the API's expected authentication. 

Also HTTP/1.1 _does_ allow a `GET` and `DELETE` request with a body, so we can't use that as a determining factor in adding to the query params. You shouldn't, but you can (and I don't think any of our APIs do it, but it's technically within spec)

2023-12-04 15:18 UTC, dragonmantank commented on packages/server-client/lib/client.ts
> +      request.type = ContentType.FORM_URLENCODED;
Key/Secret does not automatically make our requests URL encoded

2023-12-04 15:30 UTC, manchuck commented on packages/server-client/lib/enums/AuthenticationType.ts
> +     * @deprecated This method is deprecated.
Since we opened up `authType` to be public, I want to highlight that this should not be used. Maybe we can change the verbiage? @pardel any suggestions?

2023-12-04 15:30 UTC, manchuck commented on packages/server-client/lib/fileClient.ts
> +  public authType = AuthenticationType.JWT;
This change came about so we can use `ServerClient` standalone. Because this class extends `ServerClient`,  the visibility needs to stay the same. Making the `authType` public is the path of least resistance.

2023-12-04 15:33 UTC, manchuck commented on packages/server-client/lib/fileClient.ts
> +  protected saveFilePath: string = '';
you know I have not tested this out with that case. Lets file that as a seperate issue and address after this PR merges in

2023-12-04 21:50 UTC, manchuck commented on packages/server-client/lib/enums/AuthenticationType.ts
> +     * @deprecated This method is deprecated.
We devided to leave this as is for now and will update when all doc blocks PRs have been closed

2023-12-04 21:51 UTC, manchuck commented on packages/server-client/lib/client.ts
> +    // Regardless of the setting, set the auth params in the query string
You can now set the body with GET and DELETE

2023-12-04 21:51 UTC, manchuck commented on packages/server-client/lib/fileClient.ts
> +  protected saveFilePath: string = '';
This is now async safe

2023-12-05 11:38 UTC, pardel requested changes

2023-12-05 11:38 UTC, pardel commented on packages/server-client/__tests__/__dataSets__/index.ts
> +//  {
commented tests?! 
![woooah](https://github.com/Vonage/vonage-node-sdk/assets/2171/83a62bba-d67d-40a1-b9f0-6bd20462d9c1)

2023-12-05 11:38 UTC, pardel commented on packages/server-client/lib/types/APILink.ts
>  export type APILink = {
Do we really need a type for this?

2023-12-05 11:38 UTC, pardel commented on packages/server-client/package.json
> +  "contributors": [
Please add github profiles rather than emails.

2023-12-05 14:55 UTC, manchuck commented on packages/server-client/lib/types/APILink.ts
>  export type APILink = {
Yes this type is needed for when we are paging in some API's. For example, the meetings API needs to read in the link to determine if the last page has been reached:

https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/meetings/lib/meetings.ts#L82

2023-12-05 14:56 UTC, manchuck commented on packages/server-client/__tests__/__dataSets__/index.ts
> +//  {
my bad did'nt push up after I uncommented

2023-12-05 19:45 UTC, dragonmantank approved these changes

2023-12-05 20:52 UTC, merged

2023-12-05 20:52 UTC, manchuck commented on packages/server-client/package.json
> +  "contributors": [
Will address once all PRs for doc blocks have merged in