docs(audit): adding doc blocks
Vonage/vonage-node-sdk pull request #881
Opened 2023-10-27 14:12 UTC by manchuck

## Description

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-04 15:36 UTC, pardel requested changes

2023-12-04 15:36 UTC, pardel commented on packages/audit/package.json
> +      "email": "chuck@manchuck.com"
please use vonage email address

2023-12-05 11:25 UTC, pardel commented on packages/audit/package.json
> +      "email": "chuck@manchuck.com"
better - use github profile links

2023-12-05 20:55 UTC, manchuck commented on packages/audit/package.json
> +      "email": "chuck@manchuck.com"
will resolve when all doc block PRs merge in

2023-12-06 19:42 UTC, merged