docs(redact): adding doc blocks
Vonage/vonage-node-sdk pull request #887
Opened 2023-11-21 16:17 UTC by manchuck

## Description

## Motivation and Context

## Testing Details

## Example Output or Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-04 15:38 UTC, pardel requested changes

2023-12-04 15:38 UTC, pardel commented on packages/redact/package.json
>      "url": "git+https://github.com/Vonage/vonage-node-sdk.git"
Is this the right URL?

2023-12-04 15:38 UTC, pardel commented on packages/redact/package.json
> +      "name": "Chuck MANCHUCK Reeves",
please use vonage email addresses

2023-12-04 15:52 UTC, manchuck commented on packages/redact/package.json
>      "url": "git+https://github.com/Vonage/vonage-node-sdk.git"
Yup for all monorepos it will be this

2023-12-05 21:07 UTC, manchuck commented on packages/redact/package.json
> +      "name": "Chuck MANCHUCK Reeves",
will update when all doc block PRs are merged in

2023-12-06 19:40 UTC, merged