fix applications response types
Vonage/vonage-node-sdk pull request #956
Opened 2024-09-05 01:50 UTC by s-lukashenka-micoworks

- `Applications` API response type is missing a `privateKey` field.
- `Applications` API does not require all the three webhook URLs to be passed during creation but the type does not allow to omit any.

## Description

## Motivation and Context

This PR helps resolve failing type checks. The API itself works fine and has the mentioned field in its response.
Related to https://github.com/Vonage/vonage-node-sdk/issues/955.

## Testing Details

Not sure if I did things right but I ran the test suite on the PR branch.
Please, let me know if some other tests or changes are needed.

## Example Output or Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-09-05 13:40 UTC, manchuck requested changes

2024-09-05 13:40 UTC, manchuck commented on packages/applications/lib/types/Application.ts
> +     * Store this value securely.
Update to be: 

`This will only be present when the application is created, or when you cycle the public key when doing an update`

2024-09-05 23:56 UTC, s-lukashenka-micoworks commented on packages/applications/lib/types/Application.ts
> +     * Store this value securely.
@manchuck updated the doc [here](3fe8d2f890a964213e1cefbca183e198d82a50f2).

2024-09-09 10:32 UTC, manchuck approved these changes

2024-09-09 14:25 UTC, merged