Auto release from master branch via travis
Vonage/vonage-node-sdk pull request #98
Opened 2017-01-24 12:59 UTC by leggetter

2017-01-24 13:04 UTC, leggetter commented
Attempts to fix #95

2017-01-24 13:08 UTC, cbetta commented
@leggetter so I was thinking there's 2 ways to approach this:

1. Close to what you have now: On every push to Master it builds and releases a new NPM release. It should then also probably create a tag for the new version on Github. This is close to what you have now. Outstanding issues for this are: tagging on GH, and how to handle a new submission to master with the same version number.
2. My preference: Instead of listening to master we listen to tags. Tags are only pushed once and should never be updated. When someone creates a tag on GH we have Travis pick it up and do a publish to NPM. Yes, it requires an explicit push, and still requires us to also update the version number in package.json before we tag, but it's a lot more explicit.

2017-01-24 13:10 UTC, cbetta requested changes

2017-01-24 13:10 UTC, cbetta commented on .travis.yml
> +    branch: master
We should probably drop this line and only do this on tag

2017-01-24 13:14 UTC, leggetter commented
@cbetta concerns addressed in 409648b

2017-01-24 13:18 UTC, cbetta approved these changes

2017-01-24 13:18 UTC, cbetta commented
Looks good!

2017-01-24 13:54 UTC, cbetta commented
As this works on the CLI I say we can merge this.

2017-01-26 17:19 UTC, merged

2017-01-26 17:20 UTC, leggetter commented
Sorry - I forgot I was the one who was supposed to merge this 😊